# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studyBuddy2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(818, 618)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_background = QtWidgets.QFrame(Form)
        self.frame_background.setMinimumSize(QtCore.QSize(800, 600))
        self.frame_background.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(42, 44, 111, 255), stop:0.521368 rgba(28, 29, 73, 255));\n"
"border-radius: 10px;")
        self.frame_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_background.setObjectName("frame_background")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_background)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_background)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_top.setStyleSheet("background-color: none;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameTop1 = QtWidgets.QFrame(self.frame_top)
        self.frameTop1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTop1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTop1.setObjectName("frameTop1")
        self.label_title = QtWidgets.QLabel(self.frameTop1)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 241, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background-color: none; color: rgb(60, 231, 195);")
        self.label_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_title.setIndent(20)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.frameTop1)
        self.frameTop2 = QtWidgets.QFrame(self.frame_top)
        self.frameTop2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frameTop2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTop2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTop2.setObjectName("frameTop2")
        self.frame_btns = QtWidgets.QFrame(self.frameTop2)
        self.frame_btns.setGeometry(QtCore.QRect(0, 0, 100, 50))
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_5.addWidget(self.btn_maximize)
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frameTop2)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_body = QtWidgets.QFrame(self.frame_background)
        self.frame_body.setStyleSheet("background-color: none;")
        self.frame_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body.setObjectName("frame_body")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_body)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frameBody_9 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_9.setMinimumSize(QtCore.QSize(250, 230))
        self.frameBody_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_9.setObjectName("frameBody_9")
        self.frame_questionsPerDay_2 = QtWidgets.QFrame(self.frameBody_9)
        self.frame_questionsPerDay_2.setGeometry(QtCore.QRect(10, 0, 221, 221))
        self.frame_questionsPerDay_2.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 110px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_questionsPerDay_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_questionsPerDay_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_questionsPerDay_2.setObjectName("frame_questionsPerDay_2")
        self.label_questionsPerDayTitle = QtWidgets.QLabel(self.frame_questionsPerDay_2)
        self.label_questionsPerDayTitle.setGeometry(QtCore.QRect(-20, 70, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_questionsPerDayTitle.setFont(font)
        self.label_questionsPerDayTitle.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195); background-color: none;")
        self.label_questionsPerDayTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionsPerDayTitle.setObjectName("label_questionsPerDayTitle")
        self.label_questionsPerDayEdit = QtWidgets.QLabel(self.frame_questionsPerDay_2)
        self.label_questionsPerDayEdit.setGeometry(QtCore.QRect(0, 80, 221, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        self.label_questionsPerDayEdit.setFont(font)
        self.label_questionsPerDayEdit.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);background-color: none;")
        self.label_questionsPerDayEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionsPerDayEdit.setObjectName("label_questionsPerDayEdit")
        self.gridLayout.addWidget(self.frameBody_9, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameBody_1 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_1.setMinimumSize(QtCore.QSize(250, 130))
        self.frameBody_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_1.setObjectName("frameBody_1")
        self.label_todaysDateEdit = QtWidgets.QLabel(self.frameBody_1)
        self.label_todaysDateEdit.setGeometry(QtCore.QRect(10, 0, 241, 131))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        self.label_todaysDateEdit.setFont(font)
        self.label_todaysDateEdit.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);background-color: none;")
        self.label_todaysDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_todaysDateEdit.setObjectName("label_todaysDateEdit")
        self.label_todaysDateTitle = QtWidgets.QLabel(self.frameBody_1)
        self.label_todaysDateTitle.setGeometry(QtCore.QRect(0, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_todaysDateTitle.setFont(font)
        self.label_todaysDateTitle.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195); background-color: none;")
        self.label_todaysDateTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_todaysDateTitle.setObjectName("label_todaysDateTitle")
        self.gridLayout.addWidget(self.frameBody_1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameBody_4 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_4.setMinimumSize(QtCore.QSize(250, 130))
        self.frameBody_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_4.setObjectName("frameBody_4")
        self.lineEdit_questionsComplete = QtWidgets.QLineEdit(self.frameBody_4)
        self.lineEdit_questionsComplete.setGeometry(QtCore.QRect(10, 50, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lineEdit_questionsComplete.setFont(font)
        self.lineEdit_questionsComplete.setAutoFillBackground(False)
        self.lineEdit_questionsComplete.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);\n"
"background-color: rgba(28, 29, 50, 255);")
        self.lineEdit_questionsComplete.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_questionsComplete.setObjectName("lineEdit_questionsComplete")
        self.label_questionsCompleteTitle = QtWidgets.QLabel(self.frameBody_4)
        self.label_questionsCompleteTitle.setGeometry(QtCore.QRect(10, 20, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_questionsCompleteTitle.setFont(font)
        self.label_questionsCompleteTitle.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195); background-color: none;")
        self.label_questionsCompleteTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionsCompleteTitle.setObjectName("label_questionsCompleteTitle")
        self.gridLayout.addWidget(self.frameBody_4, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameBody_5 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_5.setMinimumSize(QtCore.QSize(250, 130))
        self.frameBody_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_5.setObjectName("frameBody_5")
        self.lineEdit_totalQuestions = QtWidgets.QLineEdit(self.frameBody_5)
        self.lineEdit_totalQuestions.setGeometry(QtCore.QRect(10, 50, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lineEdit_totalQuestions.setFont(font)
        self.lineEdit_totalQuestions.setAutoFillBackground(False)
        self.lineEdit_totalQuestions.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);\n"
"background-color: rgba(28, 29, 50, 255);")
        self.lineEdit_totalQuestions.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_totalQuestions.setObjectName("lineEdit_totalQuestions")
        self.label_totalQuestionsTitle = QtWidgets.QLabel(self.frameBody_5)
        self.label_totalQuestionsTitle.setGeometry(QtCore.QRect(0, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_totalQuestionsTitle.setFont(font)
        self.label_totalQuestionsTitle.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195); background-color: none;")
        self.label_totalQuestionsTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalQuestionsTitle.setObjectName("label_totalQuestionsTitle")
        self.gridLayout.addWidget(self.frameBody_5, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameBody_3 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_3.setMinimumSize(QtCore.QSize(250, 130))
        self.frameBody_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_3.setObjectName("frameBody_3")
        self.label_daysUntilTestEdit = QtWidgets.QLabel(self.frameBody_3)
        self.label_daysUntilTestEdit.setGeometry(QtCore.QRect(0, 0, 241, 131))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        self.label_daysUntilTestEdit.setFont(font)
        self.label_daysUntilTestEdit.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);background-color: none;")
        self.label_daysUntilTestEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_daysUntilTestEdit.setObjectName("label_daysUntilTestEdit")
        self.label_daysUntilTestTitle = QtWidgets.QLabel(self.frameBody_3)
        self.label_daysUntilTestTitle.setGeometry(QtCore.QRect(0, 20, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_daysUntilTestTitle.setFont(font)
        self.label_daysUntilTestTitle.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195); background-color: none;")
        self.label_daysUntilTestTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_daysUntilTestTitle.setObjectName("label_daysUntilTestTitle")
        self.gridLayout.addWidget(self.frameBody_3, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameBody_2 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_2.setMinimumSize(QtCore.QSize(250, 130))
        self.frameBody_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_2.setObjectName("frameBody_2")
        self.label_testDateTitle = QtWidgets.QLabel(self.frameBody_2)
        self.label_testDateTitle.setGeometry(QtCore.QRect(0, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_testDateTitle.setFont(font)
        self.label_testDateTitle.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195); background-color: none;")
        self.label_testDateTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_testDateTitle.setObjectName("label_testDateTitle")
        self.lineEdit_testDate = QtWidgets.QLineEdit(self.frameBody_2)
        self.lineEdit_testDate.setGeometry(QtCore.QRect(10, 50, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lineEdit_testDate.setFont(font)
        self.lineEdit_testDate.setAutoFillBackground(False)
        self.lineEdit_testDate.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);\n"
"background-color: rgba(28, 29, 50, 255);")
        self.lineEdit_testDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_testDate.setObjectName("lineEdit_testDate")
        self.gridLayout.addWidget(self.frameBody_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameBody_7 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_7.setMinimumSize(QtCore.QSize(250, 230))
        self.frameBody_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_7.setObjectName("frameBody_7")
        self.catPicture = QtWidgets.QLabel(self.frameBody_7)
        self.catPicture.setGeometry(QtCore.QRect(160, 110, 91, 111))
        self.catPicture.setText("")
        self.catPicture.setPixmap(QtGui.QPixmap("cat.PNG"))
        self.catPicture.setScaledContents(True)
        self.catPicture.setObjectName("catPicture")
        self.gridLayout.addWidget(self.frameBody_7, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameBody_6 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_6.setMinimumSize(QtCore.QSize(250, 130))
        self.frameBody_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_6.setObjectName("frameBody_6")
        self.label_questionsRemainingEdit = QtWidgets.QLabel(self.frameBody_6)
        self.label_questionsRemainingEdit.setGeometry(QtCore.QRect(0, 0, 241, 131))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        self.label_questionsRemainingEdit.setFont(font)
        self.label_questionsRemainingEdit.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);background-color: none;")
        self.label_questionsRemainingEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionsRemainingEdit.setObjectName("label_questionsRemainingEdit")
        self.label_questionsRemaining = QtWidgets.QLabel(self.frameBody_6)
        self.label_questionsRemaining.setGeometry(QtCore.QRect(0, 20, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_questionsRemaining.setFont(font)
        self.label_questionsRemaining.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195); background-color: none;")
        self.label_questionsRemaining.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionsRemaining.setObjectName("label_questionsRemaining")
        self.gridLayout.addWidget(self.frameBody_6, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameBody_8 = QtWidgets.QFrame(self.frame_body)
        self.frameBody_8.setMinimumSize(QtCore.QSize(250, 230))
        self.frameBody_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody_8.setObjectName("frameBody_8")
        self.frame_questionsPerDay = QtWidgets.QFrame(self.frameBody_8)
        self.frame_questionsPerDay.setGeometry(QtCore.QRect(20, 0, 221, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_questionsPerDay.sizePolicy().hasHeightForWidth())
        self.frame_questionsPerDay.setSizePolicy(sizePolicy)
        self.frame_questionsPerDay.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 110px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_questionsPerDay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_questionsPerDay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_questionsPerDay.setObjectName("frame_questionsPerDay")
        self.label_questionsComplete = QtWidgets.QLabel(self.frame_questionsPerDay)
        self.label_questionsComplete.setGeometry(QtCore.QRect(-20, 70, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_questionsComplete.setFont(font)
        self.label_questionsComplete.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195); background-color: none;")
        self.label_questionsComplete.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionsComplete.setObjectName("label_questionsComplete")
        self.label_questionsCompleteEdit = QtWidgets.QLabel(self.frame_questionsPerDay)
        self.label_questionsCompleteEdit.setGeometry(QtCore.QRect(10, 80, 211, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        self.label_questionsCompleteEdit.setFont(font)
        self.label_questionsCompleteEdit.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);background-color: none;")
        self.label_questionsCompleteEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_questionsCompleteEdit.setObjectName("label_questionsCompleteEdit")
        self.gridLayout.addWidget(self.frameBody_8, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_body)
        self.frame_bottom = QtWidgets.QFrame(self.frame_background)
        self.frame_bottom.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_bottom.setStyleSheet("background-color: none;")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_credits = QtWidgets.QFrame(self.frame_bottom)
        self.frame_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_credits.setObjectName("frame_credits")
        self.label_credit = QtWidgets.QLabel(self.frame_credits)
        self.label_credit.setGeometry(QtCore.QRect(0, 0, 131, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_credit.sizePolicy().hasHeightForWidth())
        self.label_credit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_credit.setFont(font)
        self.label_credit.setStyleSheet("background-color: none; color: rgb(128, 102, 168);")
        self.label_credit.setScaledContents(True)
        self.label_credit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_credit.setIndent(20)
        self.label_credit.setObjectName("label_credit")
        self.horizontalLayout_2.addWidget(self.frame_credits)
        self.frame_grip = QtWidgets.QFrame(self.frame_bottom)
        self.frame_grip.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("padding: 5px;")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_2.addWidget(self.frame_grip)
        self.verticalLayout_2.addWidget(self.frame_bottom)
        self.verticalLayout.addWidget(self.frame_background)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "Study Buddy"))
        self.btn_maximize.setToolTip(_translate("Form", "Maximize"))
        self.btn_minimize.setToolTip(_translate("Form", "Minimize"))
        self.btn_close.setToolTip(_translate("Form", "Close"))
        self.label_questionsPerDayTitle.setText(_translate("Form", "QUESTIONS PER DAY"))
        self.label_questionsPerDayEdit.setText(_translate("Form", "25"))
        self.label_todaysDateEdit.setText(_translate("Form", "10/10/2020"))
        self.label_todaysDateTitle.setText(_translate("Form", "TODAY\'S DATE"))
        self.lineEdit_questionsComplete.setText(_translate("Form", "800"))
        self.label_questionsCompleteTitle.setText(_translate("Form", "QUESTIONS COMPLETE"))
        self.lineEdit_totalQuestions.setText(_translate("Form", "1600"))
        self.label_totalQuestionsTitle.setText(_translate("Form", "TOTAL QUESTIONS"))
        self.label_daysUntilTestEdit.setText(_translate("Form", "50"))
        self.label_daysUntilTestTitle.setText(_translate("Form", "DAYS UNTIL TEST"))
        self.label_testDateTitle.setText(_translate("Form", "TEST DATE"))
        self.lineEdit_testDate.setText(_translate("Form", "12/10/2020"))
        self.label_questionsRemainingEdit.setText(_translate("Form", "1200"))
        self.label_questionsRemaining.setText(_translate("Form", "QUESTIONS REMAINING"))
        self.label_questionsComplete.setText(_translate("Form", "PERCENT COMPLETE"))
        self.label_questionsCompleteEdit.setText(_translate("Form", "25%"))
        self.label_credit.setText(_translate("Form", "By: Hung Doan"))

